### ISSUE TITLE
with_model_class(:blah) succeeds when no model_class is present

### ISSUE THREAD

**Issue by vaughncm** [sineed/neo4j-rspec#13]
Provided a model relationship and spec:

```
class Student
  include Neo4j::ActiveNode
  ...

  has_many :out, :lessons, type: 'enrolled_in'
end

RSpec.describe Student, type: model do
  ...

  it { should have_many(:lessons).with_model_class(:lies) }
end
```

The `.with_model_class(:lies)` part of the chain will succeed as if that model_class were present. Digging into the internals I believe this is related to the way `ModelClassMatcher` sets up the list of association's model classes. When there is not one present `model_class` returns nil which results in...

```
[] & [:lies] == []
=> true
```

Current assumption is it should be `actual && expected == actual`

Feel free to verify my findings as I'm still very new to both this gem and neo4jrb.

Thanks!

**Comment by sineed** [comment]
Thanks for pointing this bug!

I think that checking `model_class` is not correct. It is better to compare with `target_classes` method. [Here](https://github.com/neo4jrb/neo4j/blob/9ca280f1190ba6b76661c5c50d809a1a0e310786/lib/neo4j/active_node/has_n/association.rb#L74) you can find more about its implementation. I assume that this method always returns non-empty array so the statement `actual & expected == actual` will be correct.

**Comment by vaughncm** [comment]
Thanks!
