### ISSUE TITLE
Could the `has_one` / `has_many` matchers be improved with `chain`?

### ISSUE THREAD

**Issue by cheerfulstoic** [sineed/neo4j-rspec#2]
I haven't looked at the code closely, but it might be possible to do everything inside of the RSpec DSL:

https://relishapp.com/rspec/rspec-expectations/v/3-4/docs/custom-matchers/define-matcher-with-fluent-interface

**Comment by sineed** [comment]
I will try to rework this but I'm afraid that it will be too complex

**Comment by sineed** [comment]
Closing this
